version: "3.1" # needed for mongo 4
services:
  mongo1:
    container_name: ${MONGO_HOST}
    image: mongo:4 # needed for version 3.1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - volume-mongo:/data/db
    restart: unless-stopped
    networks:
      - mongo-network

    env_file:
      - .env
  dbseed: # Create separate service to import into mongo after mongo is loaded up.
    container_name: dbseed
    build:
      context: .
      args: # Needed for import csv - CMD
        - MONGO_DB_NAME=${MONGO_DB_NAME}
        - MONGO_TABLE_COLLECTION_NAME=${MONGO_TABLE_COLLECTION_NAME}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASS=${MONGO_PASS}
    depends_on:
    - ${MONGO_HOST}
    networks:
      - mongo-network
    
    env_file:
      - .env
volumes:
  volume-mongo:
    driver: local

networks:
  mongo-network:
    driver: bridge
